# Example Docker Compose file for running two LSSS instances with noVNC support
#
# lsss-novnc1 will be accessible on port 8081 - http://<ip>:8081
# lsss-novnc2 will be accessible on port 8082 - http://<ip>:8082
# each instance has its own home, config, and data directories to avoid conflicts
#
# docker compose -f docker-compose-2container-example.yml up
#

services:
  lsss-novnc1:
    container_name: lsss-novnc1
    image: ghcr.io/crimac-wp4-machine-learning/lsss-novnc:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:6080" # HTTP Web user interface
      #- "5900:5900" # Optional, VNC server port
    environment:
      - SCREEN_RESOLUTION=1366x768
    volumes:
      - /etc/localtime:/etc/localtime:ro # Set the container's timezone to match the host
      - ./LSSS_HOME1:/lsss:rw # lsss user home directory
      - ./LSSS_CONFIG1:/lsss/.ApplicationData/lsss:rw # LSSS ApplicationData directory
      - ./LSSS_DATA1:/lsss/LSSS_DATA:rw # LSSS_DATA directory
      #- ./path/to/datastore1:/lsss/datastore1:ro # Optional 1, replace with actual path for read-only access
      #- ./path/to/datastore2:/lsss/datastore2:rw # Optional 2, replace with actual path for read-write access
    restart: unless-stopped
  
  lsss-novnc2:
    container_name: lsss-novnc2
    image: ghcr.io/crimac-wp4-machine-learning/lsss-novnc:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:6080" # HTTP Web user interface
      #- "5900:5900" # Optional, VNC server port
    environment:
      - SCREEN_RESOLUTION=1366x768
    volumes:
      - /etc/localtime:/etc/localtime:ro # Set the container's timezone to match the host
      - ./LSSS_HOME2:/lsss:rw # lsss user home directory
      - ./LSSS_CONFIG2:/lsss/.ApplicationData/lsss:rw # LSSS ApplicationData directory
      - ./LSSS_DATA2:/lsss/LSSS_DATA:rw # LSSS_DATA directory
      #- ./path/to/datastore1:/lsss/datastore1:ro # Optional 1, replace with actual path for read-only access
      #- ./path/to/datastore2:/lsss/datastore2:rw # Optional 2, replace with actual path for read-write access
    restart: unless-stopped
